apiVersion: afterpush.dev/v1
kind: Application

metadata:
  name: afterpush-api

spec:
  profile: eks

  image:
    repository: 833090513321.dkr.ecr.eu-central-1.amazonaws.com/afterpush-api
    tag: cb861fe5538164d73e358b26722adc66384f899e

  port: 3000

  health:
    path: /health

  ingress:
    enabled: false
    host: afterpush.local

  scaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilization: 50

  monitoring:
    enabled: false