{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: Probe

metadata:
  name: {{ .Values.application.name }}-http
  labels:
    release: monitoring
    application: {{ .Values.application.name | quote }}

spec:
  jobName: {{ printf "%s-blackbox" .Values.application.name | quote }}

  interval: 15s

  module: afterpush_http_2xx

  prober:
    url: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115

  targets:
    staticConfig:
      static:
        - {{ printf "http://%s%s" .Values.ingress.host .Values.probes.readiness.path | quote }}
      labels:
        application: {{ .Values.application.name | quote }}
{{- end }}