{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: {{ .Values.application.name }}
  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app: {{ .Values.application.name }}

  endpoints:
    - port: http
      path: /metrics
      interval: 15s

      relabelings:
        - targetLabel: application
          replacement: {{ .Values.application.name | quote }}
{{- end }}