application:
  name: afterpush-api

image:
  repository: 833090513321.dkr.ecr.eu-central-1.amazonaws.com/afterpush-api
  tag: cb861fe5538164d73e358b26722adc66384f899e
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

config:
  appEnv: eks
  logLevel: info

ingress:
  enabled: false
  className: ""
  host: ""
  path: /
  pathType: Prefix

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

probes:
  readiness:
    path: /health
    initialDelaySeconds: 2
    periodSeconds: 5
  liveness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 10

monitoring:
  enabled: false